<a href="https://colab.research.google.com/github/veenasjayanthan/python-projects/blob/main/newdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np


In [ ]:
from google.colab import files
uploaded=files.upload()
df=pd.read_csv("/content/housing.csv")
#df.head(10)
df

Saving housing.csv to housing (1).csv


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [ ]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.NaN,strategy='median')
df['total_bedrooms']=imputer.fit_transform(df['total_bedrooms'].values.reshape(-1,1))


In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['ocean_proximity']=le.fit_transform(df['ocean_proximity'])


In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

       ocean_proximity  
0                    3  
1                    3  
2                    3  
3                    3  
4                    3  
...                ...  
20635                1  
20636                1  
20637                1  
20638                1  
20639                1  

[20640 rows x 10 columns]

In [ ]:
df.values

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  8.3252e+00,
         4.5260e+05,  3.0000e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  8.3014e+00,
         3.5850e+05,  3.0000e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  7.2574e+00,
         3.5210e+05,  3.0000e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  1.7000e+00,
         9.2300e+04,  1.0000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  1.8672e+00,
         8.4700e+04,  1.0000e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  2.3886e+00,
         8.9400e+04,  1.0000e+00]])

In [ ]:
x=df.drop(["median_house_value"],axis=1).values
x

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  1.2600e+02,
         8.3252e+00,  3.0000e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  1.1380e+03,
         8.3014e+00,  3.0000e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  1.7700e+02,
         7.2574e+00,  3.0000e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  4.3300e+02,
         1.7000e+00,  1.0000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  3.4900e+02,
         1.8672e+00,  1.0000e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  5.3000e+02,
         2.3886e+00,  1.0000e+00]])

In [ ]:
y=df["median_house_value"]
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.97703285,
         2.34476576,  1.2910888 ],
       [-1.32284391,  1.04318455, -0.60701891, ...,  1.66996103,
         2.33223796,  1.2910888 ],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.84363692,
         1.7826994 ,  1.2910888 ],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.17404163,
        -1.14259331, -0.11673923],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.39375258,
        -1.05458292, -0.11673923],
       [-0.83369581,  1.75014627, -1.00430931, ...,  0.07967221,
        -0.78012947, -0.11673923]])

In [ ]:
x[0]

array([-1.32783522,  1.05254828,  0.98214266, -0.8048191 , -0.97247648,
       -0.9744286 , -0.97703285,  2.34476576,  1.2910888 ])

In [ ]:
x[1]

array([-1.32284391,  1.04318455, -0.60701891,  2.0458901 ,  1.35714343,
        0.86143887,  1.66996103,  2.33223796,  1.2910888 ])

In [ ]:
x[2]

array([-1.33282653,  1.03850269,  1.85618152, -0.53574589, -0.82702426,
       -0.82077735, -0.84363692,  1.7826994 ,  1.2910888 ])

In [ ]:
x[4]

array([-1.33781784,  1.03850269,  1.85618152, -0.46240395, -0.61242263,
       -0.75984669, -0.62915718, -0.012881  ,  1.2910888 ])

In [ ]:
x[9]

array([-1.33781784,  1.03382082,  1.85618152,  0.418616  ,  0.40574287,
        0.1108437 ,  0.56094383, -0.09446958,  1.2910888 ])

In [ ]:
x[3]

array([-1.33781784,  1.03850269,  1.85618152, -0.62421459, -0.71972345,
       -0.76602806, -0.73378144,  0.93296751,  1.2910888 ])

In [ ]:
x[5]

array([-1.33781784,  1.03850269,  1.85618152, -0.786942  , -0.77218163,
       -0.89407076, -0.80178721,  0.08744664,  1.2910888 ])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=4)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation  #Dense layer, also called fully-connected layer, 
                                                      #refers to the layer whose inside neurons connect to every neuron in the preceding layer.
                                                      #Dense Layer is simple layer of neurons in which each neuron receives input from all the neurons of previous layer
from tensorflow.keras.optimizers import Adam                                              
from tensorflow.keras.layers import*
from keras.layers.attention.multi_head_attention import activation

In [ ]:
def houseprediction():
  model=Sequential() #innitialize the ANN
  model.add(Dense(128, activation="relu", input_dim=9))
  model.add(Dense(64, activation="relu"))
  model.add(Dense(32, activation="relu"))
  model.add(Dense(1))
  model.compile(optimizer="rmsprop",loss="mse",metrics=["mae"]) #An optimizer is a function or an algorithm that modifies the attributes of the neural network, 
                                                                #such as weights and learning rate. 
                                                                #Thus, it helps in reducing the overall loss and improve the accuracy
  return model

In [ ]:
                        #Increasing kernel size means effectively increasing the total number of parameters. So,
                         # it is expected that the model has a higher complexity to address a given problem. So it should perform better at least for a particular training set.
k=4                     #a method of using a linear classifier to solve a non-linear problem                       
num_val_samples= len(x_train)
num_epochs=10
all_scores=[]



In [ ]:
model = houseprediction()                                           #verbose is the choice that how you want to see the output of your Nural Network while it's training.
                                                                            # If you set verbose = 0, It will show nothing.
history=model.fit(x_train,y_train,epochs=num_epochs,batch_size=64,verbose=1,validation_data=(x_test,y_test))

#Validation loss is used to ascertain performance on an entire epoch after the training loss has been calculated and weight updates have been completed.





#The validation set is a set of data, separate from the training set, that is used to validate our model performance during training. 
#This validation process gives information that helps us tune the model's hyperparameters and configurations accordingly.

Epoch 1/10
217/217 [==============================] - 2s 3ms/step - loss: 56107945984.0000 - mae: 206679.8125 - val_loss: 54475894784.0000 - val_mae: 203600.2031
Epoch 2/10
217/217 [==============================] - 1s 3ms/step - loss: 52193185792.0000 - mae: 197800.0938 - val_loss: 46356230144.0000 - val_mae: 184509.1406
Epoch 3/10
217/217 [==============================] - 1s 3ms/step - loss: 38197641216.0000 - mae: 162536.0000 - val_loss: 27023519744.0000 - val_mae: 131132.1562
Epoch 4/10
217/217 [==============================] - 1s 3ms/step - loss: 18509193216.0000 - mae: 101711.8906 - val_loss: 11822204928.0000 - val_mae: 78319.7422
Epoch 5/10
217/217 [==============================] - 1s 3ms/step - loss: 10670871552.0000 - mae: 74106.9297 - val_loss: 9271783424.0000 - val_mae: 69523.3672
Epoch 6/10
217/217 [==============================] - 1s 3ms/step - loss: 8799894528.0000 - mae: 67258.4297 - val_loss: 7849332736.0000 - val_mae: 63893.0508
Epoch 7/10
217/217 [================

In [ ]:
model.evaluate(x_test,y_test)[1]

213/213 [==============================] - 0s 2ms/step - loss: 5362018304.0000 - mae: 52557.5508


52557.55078125

In [ ]:
y_test

6939     175200.0
8032     314700.0
18877     90000.0
4882     123100.0
5409     350900.0
           ...   
13321     91800.0
16999    500001.0
15214    263600.0
8234     106300.0
18857     56000.0
Name: median_house_value, Length: 6812, dtype: float64

In [ ]:
prediction=model.predict(x_test)
prediction

213/213 [==============================] - 0s 1ms/step


array([[193068.11],
       [256512.67],
       [190382.77],
       ...,
       [272514.7 ],
       [158545.31],
       [144501.52]], dtype=float32)

In [ ]:
test_input=[[-1.32783522,  1.05254828,  0.98214266, -0.8048191 , -0.97247648,   #0
       -0.9744286 , -0.97703285,  2.34476576,  1.2910888 ]]
print("actual output is:452600.0")

print("predicted output is:",model.predict(test_input))

actual output is:452600.0
1/1 [==============================] - 0s 31ms/step
predicted output is: [[406750.3]]


In [ ]:
test_input=[[-1.33781784,  1.03850269,  1.85618152, -0.46240395, -0.61242263,  #4
       -0.75984669, -0.62915718, -0.012881  ,  1.2910888]]
print("actual output is:342200.0	")

print("predicted output is:",model.predict(test_input))

actual output is:342200.0	
1/1 [==============================] - 0s 28ms/step
predicted output is: [[265957.53]]


In [ ]:
test_input=[[-1.33781784,  1.03382082,  1.85618152,  0.418616  ,  0.40574287,   #9
        0.1108437 ,  0.56094383, -0.09446958,  1.2910888]]
print("actual output is:261100.0")

print("predicted output is:",model.predict(test_input))

actual output is:261100.0
1/1 [==============================] - 0s 30ms/step
predicted output is: [[273410.]]


In [ ]:
test_input=[[-1.33781784,  1.03850269,  1.85618152, -0.62421459, -0.71972345,
       -0.76602806, -0.73378144,  0.93296751,  1.2910888 ]]                      #3
print("actual output is:341300.0")

print("predicted output is:",model.predict(test_input))

actual output is:341300.0
1/1 [==============================] - 0s 33ms/step
predicted output is: [[328051.47]]


In [ ]:
test_input=[[-1.33781784,  1.03850269,  1.85618152, -0.786942  , -0.77218163,
       -0.89407076, -0.80178721,  0.08744664,  1.2910888 ]]                      #5
print("actual output is:269700.0")

print("predicted output is:",model.predict(test_input))

actual output is:269700.0
1/1 [==============================] - 0s 33ms/step
predicted output is: [[269914.62]]


In [ ]:
test_input=[[-1.32284391,  1.04318455, -0.60701891,  2.0458901 ,  1.35714343,
        0.86143887,  1.66996103,  2.33223796,  1.2910888]]                      #1
print("actual output is:358500.0	")

print("predicted output is:",model.predict(test_input))

actual output is:358500.0	
1/1 [==============================] - 0s 25ms/step
predicted output is: [[415897.28]]


In [ ]:
test_input=[[-1.33282653,  1.03850269,  1.85618152, -0.53574589, -0.82702426,
       -0.82077735, -0.84363692,  1.7826994 ,  1.2910888]]                      #2
print("actual output is:352100.0	")

print("predicted output is:",model.predict(test_input))

actual output is:352100.0	
1/1 [==============================] - 0s 28ms/step
predicted output is: [[392314.53]]


In [ ]:
from sklearn.metrics import r2_score
score=r2_score(y_test,prediction)
score

0.557861673268189